#!/bin/bash

if   [ $# = 0 ]; then
    python3 src/main.py
elif [ $# = 1 ]; then
    python3 src/main.py < $1
elif [ $# = 2 ]; then
    python3 src/main.py < $1 > $2
else
    echo "Usage: ./proj1 [input] [output]"
    exit 1
fi
